# Generated by Django 4.1.6 on 2023-02-04 17:11

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the problem', max_length=250)),
                ('description', models.CharField(help_text='Description of the problem', max_length=1024)),
                ('restrictions', models.CharField(help_text='Restrictions of the problem or other mentions', max_length=1024)),
                ('difficulty_level', django_fsm.FSMField(choices=[('School', 'School'), ('Basic', 'Basic'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('High', 'High')], default='School', help_text='Level of the problem', max_length=50)),
                ('status', django_fsm.FSMField(choices=[('Solved', 'Solved'), ('Unsolved', 'Unsolved'), ('Attempted', 'Attempted'), ('Bookmarked', 'Bookmarked')], default='Unsolved', help_text='Status of the problem', max_length=50)),
                ('task_description', models.CharField(help_text='Describe what user should do in the current problem', max_length=2048)),
                ('points', models.IntegerField(default=100, help_text='How much points you can get if you solve the problem')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', django_fsm.FSMField(choices=[('ARRAYS', 'ARRAYS'), ('STRINGS', 'STRINGS'), ('MATRIX', 'MATRIX'), ('NUMBERS', 'NUMBERS'), ('SORTING', 'SORTING')], default='ARRAYS', help_text='Topic of the problem', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemExamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_description', models.CharField(help_text='Examples for problems', max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='topic_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.problemtopics'),
        ),
    ]
