# Generated by Django 4.1.6 on 2023-02-04 17:17

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtopics',
            name='topic',
            field=django_fsm.FSMField(choices=[('Arrays', 'Arrays'), ('Strings', 'Strings'), ('Matrix', 'Matrix'), ('Numbers', 'Numbers'), ('Sorting', 'sorting')], default='Arrays', help_text='Topic of the problem', max_length=50),
        ),
    ]
