# Generated by Django 4.1.6 on 2023-02-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restapi', '0002_alter_problemtopics_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(help_text='Description of the problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='restrictions',
            field=models.TextField(
                help_text='Restrictions of the problem or other mentions'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='task_description',
            field=models.TextField(
                help_text='Describe what user should do in the current problem',
                max_length=2048
            ),
        ),
    ]
