# Generated by Django 4.1.6 on 2023-04-08 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0003_alter_problem_description_alter_problem_restrictions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMailRepeatedFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('fail_traceback', models.TextField()),
                ('arg_info', models.TextField()),
            ],
            options={
                'db_table': 'send_mail_repeated_failure',
            },
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(help_text='Status of the submission', max_length=50)),
                ('lang', models.CharField(help_text='Language', max_length=20)),
                ('test_cases', models.CharField(help_text='Test cases passed', max_length=20)),
                ('code_submitted', models.TextField(help_text='Code submitted')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_coding_points', models.IntegerField(default=0, help_text='Total points')),
                ('total_problems_solved', models.IntegerField(default=0, help_text='Total problems solved')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
