# Generated by Django 4.1.6 on 2023-05-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_rename_rank_usersrank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersrank',
            old_name='username',
            new_name='user',
        ),
    ]
