# Generated by Django 4.1.6 on 2023-05-15 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0006_rename_username_usersrank_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='status',
        ),
        migrations.CreateModel(
            name='UsersProblemsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[('Solved', 'Solved'), ('Unsolved', 'Unsolved'), ('Attempted', 'Attempted'), ('Bookmarked', 'Bookmarked')], default='Unsolved', help_text='Status of the problem', max_length=50)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
