# Generated by Django 4.1.6 on 2023-05-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_remove_problem_status_usersproblemsstatus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersproblemsstatus',
            table='users_problems_status',
        ),
    ]
