# Generated by Django 4.1.6 on 2023-05-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_alter_usersproblemsstatus_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubmission',
            new_name='UserSolutionSubmitted',
        ),
        migrations.AlterModelTable(
            name='problemexamples',
            table='restapi_problem_examples',
        ),
        migrations.AlterModelTable(
            name='problemtopics',
            table='restapi_problem_topics',
        ),
        migrations.AlterModelTable(
            name='usersolutionsubmitted',
            table='restapi_user_solution_submitted',
        ),
        migrations.AlterModelTable(
            name='usersproblemsstatus',
            table='restapi_users_problems_status',
        ),
        migrations.AlterModelTable(
            name='usersrank',
            table='restapi_users_rank',
        ),
    ]
