# Generated by Django 4.1.6 on 2023-05-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_rename_usersubmission_usersolutionsubmitted_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sendmailrepeatedfailure',
            table='restapi_send_mail_repeated_failure',
        ),
    ]
