# Generated by Django 4.1.6 on 2023-05-20 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_alter_sendmailrepeatedfailure_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_example',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.problemexamples'),
        ),
        migrations.AlterField(
            model_name='problemexamples',
            name='example_description',
            field=models.CharField(default='Nu exista', help_text='Examples for problems', max_length=2048),
        ),
    ]
