# Generated by Django 4.1.6 on 2023-06-03 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0011_remove_problemexamples_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='code_snapshot',
            field=models.TextField(blank=True, default='<no_code_provided>', help_text='Code snapshot which will help user to start coding', max_length=2048),
        ),
        migrations.AddField(
            model_name='usersolutionsubmitted',
            name='points',
            field=models.IntegerField(default=0, help_text='Total points obtained'),
        ),
        migrations.AddField(
            model_name='usersolutionsubmitted',
            name='problem',
            field=models.ForeignKey(default=1, help_text='Give an example for current problem', on_delete=django.db.models.deletion.CASCADE, to='restapi.problem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersolutionsubmitted',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
