# Generated by Django 4.1.6 on 2023-06-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_remove_problemexamples_problem_problem_code_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code_snapshot',
            field=models.TextField(blank=True, default='No_code_provided', help_text='Code snapshot which will help user to start coding', max_length=2048),
        ),
    ]
