# Generated by Django 4.1.6 on 2023-06-07 20:32

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_remove_problemexamples_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersolutionsubmitted',
            name='status',
            field=django_fsm.FSMField(choices=[('Problem Solved', 'Problem Solved'), ('Problem Unsolved', 'Problem Unsolved'), ('Problem Partial Solved', 'Problem Partial Solved')], default='Problem Unsolved', help_text='Status of the submission', max_length=50),
        ),
    ]
