# Generated by Django 4.1.6 on 2023-06-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0015_alter_usersolutionsubmitted_test_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersolutionsubmitted',
            name='test_cases',
            field=models.CharField(help_text='Test cases passed', max_length=100),
        ),
    ]
