# Generated by Django 4.1.6 on 2023-06-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0016_alter_usersolutionsubmitted_test_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersolutionsubmitted',
            name='points',
            field=models.FloatField(default=0, help_text='Total points obtained'),
        ),
    ]
